"""change progress to float

Revision ID: dfc3431ff96a
Revises: 8ab53184eaf8
Create Date: 2026-07-12 18:09:22.090190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc3431ff96a'
down_revision: Union[str, Sequence[str], None] = '8ab53184eaf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_challenges', 'id',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_challenges_id_seq'::regclass)"))
    op.alter_column('user_challenges', 'progress',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_challenges', 'progress',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_challenges', 'id',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_challenges_id_seq'::regclass)"))
    # ### end Alembic commands ###
